#pragma checksum "..\..\..\View\RecentFileButton.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8256875357BCF15005E9DA83CA3EC0361BAE00F94EBDBEFDC1A68D503E0FC7C8"
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion.UI.Xaml.Diagram.Controls;
using Syncfusion.UI.Xaml.Diagram.Panels;
using Syncfusion.UI.Xaml.Diagram.Utility;
using System;
using System.Collections;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.brainstormingdiagram.wpf;
using syncfusion.brainstormingdiagram.wpf.Utility;
using syncfusion.brainstormingdiagram.wpf.View;
using syncfusion.brainstormingdiagram.wpf.ViewModel;


namespace syncfusion.brainstormingdiagram.wpf.View {
    
    
    /// <summary>
    /// RecentFileButton
    /// </summary>
    public partial class RecentFileButton : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 1 "..\..\..\View\RecentFileButton.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.brainstormingdiagram.wpf.View.RecentFileButton recentFileControl;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\View\RecentFileButton.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFileName;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\View\RecentFileButton.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtFileName;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\View\RecentFileButton.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PART_Menu;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.brainstormingdiagram.wpf;component/view/recentfilebutton.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\View\RecentFileButton.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.recentFileControl = ((syncfusion.brainstormingdiagram.wpf.View.RecentFileButton)(target));
            return;
            case 2:
            this.lblFileName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.txtFileName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.PART_Menu = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            
            #line 75 "..\..\..\View\RecentFileButton.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.PART_Menu_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 76 "..\..\..\View\RecentFileButton.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.PART_Menu_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 77 "..\..\..\View\RecentFileButton.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.PART_Menu_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 78 "..\..\..\View\RecentFileButton.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.PART_Menu_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

