#pragma checksum "..\..\..\Views\DocumentToolbar.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "1F7A0FE7E6163B5D0E0B6C12BD3BC2461BD30F1B05DE01DCF8DC45774DAE19B2"
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion.Windows.PdfViewer;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.pdfviewerdemos.wpf;


namespace syncfusion.pdfviewerdemos.wpf {
    
    
    /// <summary>
    /// DocumentToolbar
    /// </summary>
    public partial class DocumentToolbar : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 6 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel toolBar;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnOpen;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnPrint;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGoToFirstPage;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGoToPreviousPage;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtCurrentPageIndex;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblTotalPageCount;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGoToNextPage;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGoToLastPage;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnZoomIn;
        
        #line default
        #line hidden
        
        
        #line 182 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnZoomOut;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\Views\DocumentToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbCurrentZoomLevel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.pdfviewerdemos.wpf;component/views/documenttoolbar.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\DocumentToolbar.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.toolBar = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 2:
            this.btnOpen = ((System.Windows.Controls.Button)(target));
            return;
            case 3:
            this.btnPrint = ((System.Windows.Controls.Button)(target));
            return;
            case 4:
            this.btnGoToFirstPage = ((System.Windows.Controls.Button)(target));
            return;
            case 5:
            this.btnGoToPreviousPage = ((System.Windows.Controls.Button)(target));
            return;
            case 6:
            this.txtCurrentPageIndex = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.lblTotalPageCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.btnGoToNextPage = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.btnGoToLastPage = ((System.Windows.Controls.Button)(target));
            return;
            case 10:
            this.btnZoomIn = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.btnZoomOut = ((System.Windows.Controls.Button)(target));
            return;
            case 12:
            this.cmbCurrentZoomLevel = ((System.Windows.Controls.ComboBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

